#!/bin/bash

# run integration test with language definition and test input

if [ $# -eq 0 ]; then
    s=test
    t=test
elif [ $# -eq 1 ]; then
    s=${1}
    t=${s}
else
    s=${1}
    t=${2}
fi

time ./te ${s} < ${t}.main.txt > tttt
echo '  <  ACTUAL'
echo '  >  EXPECTED'
echo ''
diff -bB tttt ${t}.main.key
