#!/bin/bash
# doTest - run PyElly integration tests
s=${1:-test}
echo system= ${s}
if [ ${s} == 'doctor'   ]; then x='-noLang'; fi
if [ ${s} == 'indexing' ]; then x='-d 8'   ; fi
if [ ${s} == 'chinese'  ]; then x='-g tra' ; fi
if [ ${s} == 'disambig' ]; then x='-noLang -p' ; fi
rm -f *.elly.bin

if [ -t 0 ]; then
    echo standard input not redirected
    python ellyMain.py ${x} $2 $3 $4 ${s} < ${s}.main.txt &> ttmm
else
    echo standard input from file already
    python ellyMain.py ${x} $2 $3 $4 ${s}                 &> ttmm
fi

egrep FAIL\|$'\r'\|'^ [^ ]' ttmm
